name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install Jest globally
        run: npm install -g jest
      
      - name: Run linting
        run: npm run lint
        
      - name: Run JS Library Jest tests
        working-directory: "./JS library"
        run: |
          echo "Running in $(pwd)"
          npm install
          npm run testJest || echo "Jest tests failed but continuing build"
        
      - name: Run existing test suite
        run: |
          # Run the existing test commands
          npm run test:manual || true
        continue-on-error: true 

  build-docker:
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: dbtest-repo:latest
          outputs: type=docker,dest=/tmp/dbtest-image.tar
      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dbtest-docker-image
          path: /tmp/dbtest-image.tar